### ISSUE TITLE
Pick and place using aruco markers

### ISSUE THREAD

**Issue by ManasviniSrini** [moveit/moveit_calibration#144]
Hello,
This is a beginner question about the workflow for pick and place using moveit and aruco markers. I have a ur5 robot and I did the hand eye calibration for my lucid camera using the moveit_calibration_gui. I was wondering what would be the next steps to achieve a pick and place of an object with the aruco marker on it. Any tutorials or documentation would really help. Thanks !

**Comment by JStech** [comment]
Glad you were able to use MoveIt Calibration! There is a [pick-and-place tutorial](https://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html) in the MoveIt documentation. Take a look there.

For more help with MoveIt, please ask questions at [robotics.stackexchange.com](https://robotics.stackexchange.com/).
