### ISSUE TITLE
Copyright Holder?

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_calibration#3]
The LICENSE file assigns the copyright to "ROS Planning" - but that's not a real legal entity to hold the copyright. Most of the files inside are assigned to Intel Corporation - I'd suggest the LICENSE file either be to match "Copyright 2019 Intel Corporation". You can also assign future work to the Open Source Robotics Foundation, which is a real legal entity (or a MoveIt foundation someday).

**Comment by mikeferguson** [comment]
@davetcoleman

**Comment by felixvd** [comment]
@RoboticsYY
